import { CandidateItem } from '@/types';

export const SAMPLE_JOB = {
  title: 'Backend Software Engineer',
  company: 'Apex Cloud Technologies',
  seniority: 'mid',
  description:
    'About the role:\nAs a Backend Software Engineer at Apex Cloud Technologies, you will contribute to designing, implementing, and operating high-performance distributed backend services.\n\nTech Stack & Core Systems:\n- Primary Languages: Python, Go, or Ruby\n- Architecture & Frameworks: FastAPI, Ruby on Rails, or Gin, REST APIs, GraphQL\n- Data & Storage: PostgreSQL, Redis, Event Sourcing, Domain-Driven Design (DDD)\n- Background Jobs & Messaging: Sidekiq, Celery, or RabbitMQ, AWS (S3, SQS, RDS, EKS)\n- Observability & Testing: Datadog, Prometheus, RSpec / PyTest\n\nRequirements:\n- Strong experience in backend engineering and building scalable web APIs\n- Solid understanding of relational database design, query optimization, and transaction isolation\n- Deep understanding of HTTP protocol, RESTful standards, and microservices communication\n- Hands-on experience with asynchronous messaging, event queues, or background job processing\n- Familiarity with CI/CD pipelines, Docker containerization, and Git workflows\n- Solid grasp of software design patterns, Clean Architecture, and SOLID principles\n- Strong problem-solving abilities and clear technical communication in written and spoken English\n\nWhat we offer:\n- Flexible work schedule and remote-first culture\n- Comprehensive health coverage and wellness stipends\n- Annual continuous learning and tech equipment allowance ($3,000/year)\n- Collaborative engineering team focusing on high engineering standards and modern toolchains',
} as const;

export const SAMPLE_CANDIDATES: CandidateItem[] = [
  {
    id: 'sample-1',
    name: 'Andrei Popescu',
    cvFileName: 'Andrei_Popescu_Backend_Engineer.pdf',
    fileSizeFormatted: '1.9 MB',
    cvRawText:
      'Andrei Popescu\nEmail: andrei.popescu@example.com | Location: Cluj-Napoca, Romania | Portfolio: github.com/andrei-popescu-dev\n\nPROFESSIONAL SUMMARY\nSenior Backend Engineer with 5+ years of experience engineering high-throughput microservices, distributed data pipelines, and REST/GraphQL APIs. Core expertise in Python (FastAPI), Ruby on Rails, and PostgreSQL.\n\nTECHNICAL COMPETENCIES\n- Languages: Python, Ruby, Go, SQL, Bash\n- Frameworks: FastAPI, Ruby on Rails, Django, RSpec, PyTest\n- Databases & In-Memory: PostgreSQL, Redis, DynamoDB\n- Messaging & Queues: RabbitMQ, Sidekiq, AWS SQS, Celery\n- Architecture: Domain-Driven Design (DDD), Event Sourcing, Microservices, RESTful APIs, GraphQL\n- DevOps & Cloud: AWS (S3, RDS, EKS), Docker, Kubernetes, Terraform, Datadog\n\nWORK EXPERIENCE\nSenior Backend Engineer | CloudScale Systems\nMarch 2022 - Present (2 years 6 months)\n- Spearheaded the migration of core monolithic services into event-driven microservices using Python (FastAPI) and Ruby on Rails.\n- Designed distributed task queues with Redis and Sidekiq processing over 12 million asynchronous jobs daily.\n- Optimized PostgreSQL indexing and partition strategies, lowering p99 API query latency from 320ms to 45ms.\n- Built GraphQL federation gateways handling cross-service schema stitching and high-volume data resolution.\n- Integrated Datadog distributed tracing, synthetic checks, and APM alerting to maintain 99.98% service uptime.\n\nBackend Software Developer | Horizon Fintech Labs\nJune 2019 - February 2022 (2 years 9 months)\n- Developed secure payment processing endpoints with Python and PostgreSQL complying with PCI-DSS standards.\n- Authored automated test suites with PyTest and RSpec, raising test coverage from 68% to 94%.\n- Containerized development workflows using Docker Compose, reducing team developer onboarding time by 50%.\n\nEDUCATION\nBachelor of Science in Computer Science | Technical University of Cluj-Napoca (2015 - 2019)',
  },
  {
    id: 'sample-2',
    name: 'Mihai Ionescu',
    cvFileName: 'Mihai_Ionescu_Distributed_Systems.pdf',
    fileSizeFormatted: '1.7 MB',
    cvRawText:
      'Mihai Ionescu\nEmail: mihai.ionescu@example.com | Location: Bucharest, Romania | Website: mihai-ionescu.dev\n\nPROFESSIONAL SUMMARY\nDistributed Systems Backend Developer with 4 years of experience architecting fault-tolerant streaming pipelines, high-performance Go and Python services, and distributed storage systems.\n\nTECHNICAL SKILLS\n- Languages: Go, Python, SQL, C++\n- Frameworks: FastAPI, Gin, Chi, gRPC, Protobuf\n- Databases: PostgreSQL, CockroachDB, Redis\n- Messaging & Streaming: Apache Kafka, RabbitMQ, EventStore\n- Practices: Event Sourcing, CQRS, Domain-Driven Design, TDD\n- Infrastructure: Docker, Kubernetes, AWS EKS, Prometheus, Grafana\n\nWORK EXPERIENCE\nDistributed Systems Engineer | NexaStream Technologies\nMay 2022 - Present (2 years 4 months)\n- Engineered event-driven backend services in Go and Python FastAPI utilizing Event Sourcing and CQRS patterns.\n- Constructed real-time audit ledger consuming Kafka topics with at-least-once delivery guarantees.\n- Tuned PostgreSQL connection pools with PgBouncer and optimized complex analytical query plans.\n- Implemented gRPC microservice communication with mutual TLS and protobuf schema contracts.\n\nBackend Software Engineer | DataFlow Solutions\nSeptember 2020 - April 2022 (1 year 8 months)\n- Implemented high-throughput RESTful ingestion APIs with Python FastAPI and PostgreSQL.\n- Deployed monitoring stacks using Prometheus metrics and Grafana dashboards for cluster observability.\n- Automated CI/CD deployment pipelines using GitHub Actions and ArgoCD on AWS Kubernetes.\n\nEDUCATION\nBachelor of Science in Computer Science | University Politehnica of Bucharest (2016 - 2020)',
  },
  {
    id: 'sample-3',
    name: 'Radu Dumitrescu',
    cvFileName: 'Radu_Dumitrescu_Rails_Architect.pdf',
    fileSizeFormatted: '2.1 MB',
    cvRawText:
      'Radu Dumitrescu\nEmail: radu.dumitrescu@example.com | Location: Timi\u0219oara, Romania | GitHub: github.com/radu-dumitrescu\n\nPROFESSIONAL SUMMARY\nStaff Software Engineer with 6+ years of dedicated experience in Ruby on Rails, hexagonal software architecture, and distributed cloud backends. Passionate about Domain-Driven Design, clean code, and zero-downtime database migrations.\n\nCORE SKILLS\n- Languages: Ruby, Python, SQL, TypeScript\n- Frameworks & Libraries: Ruby on Rails 7, Dry-Rb, Sidekiq Enterprise, RSpec, GraphQL-Ruby\n- Data & Storage: PostgreSQL, Redis, AWS Aurora, Elasticsearch\n- Cloud & Infrastructure: AWS (S3, SQS, RDS, EKS), Docker, Datadog\n- Architectural Patterns: Domain-Driven Design (DDD), Hexagonal Architecture, Event-Driven Systems\n\nWORK EXPERIENCE\nLead Backend Engineer | Orbit Interactive Cloud\nJanuary 2021 - Present (3 years 8 months)\n- Led a team of 7 engineers developing core e-commerce backend in Ruby on Rails and Dry-Rb.\n- Architected enterprise background processing subsystem with Sidekiq and AWS SQS, handling 25,000 jobs/minute.\n- Implemented GraphQL APIs serving web and mobile clients with comprehensive batch loading via GraphQL-Batch.\n- Managed zero-downtime PostgreSQL schema migrations for enterprise databases storing over 80 million rows.\n- Established Datadog SLO dashboards and latency monitors that reduced incident MTTR by 45%.\n\nSoftware Developer | Veloce Platform\nJune 2018 - December 2020 (2 years 7 months)\n- Developed and maintained microservices using Ruby on Rails and Python.\n- Wrote thorough automated unit and integration tests with RSpec and Minitest.\n- Designed database schemas and normalization structures in PostgreSQL.\n\nEDUCATION\nB.Eng. in Computer Engineering | Politehnica University of Timi\u0219oara (2014 - 2018)',
  },
  {
    id: 'sample-4',
    name: 'Bogdan Marinescu',
    cvFileName: 'Bogdan_Marinescu_Cloud_Backend.pdf',
    fileSizeFormatted: '1.5 MB',
    cvRawText:
      'Bogdan Marinescu\nEmail: bogdan.marinescu@example.com | Location: Ia\u0219i, Romania | LinkedIn: linkedin.com/in/bogdan-marinescu-fictional\n\nPROFESSIONAL SUMMARY\nBackend Software Engineer with 5 years of experience building resilient cloud services, microservices, and database solutions using C#/.NET Core and Python. Experienced in Domain-Driven Design and eager to expand deep into Ruby on Rails and Go.\n\nSKILLS & EXPERTISE\n- Languages: C#, Python, SQL, Go\n- Frameworks: .NET Core, ASP.NET Web API, FastAPI, Entity Framework Core, Dapper\n- Storage: PostgreSQL, MS SQL Server, Redis\n- Cloud & Containers: AWS, Docker, Kubernetes, Terraform\n- Architecture: Microservices, Clean Architecture, DDD, REST APIs, Message Queuing (RabbitMQ)\n\nWORK EXPERIENCE\nSenior Software Engineer | Apex Global Technologies\nAugust 2021 - Present (3 years 1 month)\n- Designed and maintained high-throughput REST APIs and microservices using .NET Core and Python FastAPI.\n- Implemented caching layers using Redis clusters, cutting database read loads by 55%.\n- Migrated legacy data storage to PostgreSQL, authoring complex migration scripts and optimizing indexing strategies.\n- Collaborated in an agile cross-functional team utilizing Domain-Driven Design and event-driven patterns with RabbitMQ.\n\nSoftware Engineer | Nordic Soft Enterprises\nJuly 2019 - July 2021 (2 years 1 month)\n- Built internal tooling and external partner APIs with ASP.NET Core and PostgreSQL.\n- Implemented Docker containerization for development and production staging environments.\n- Wrote automated integration tests with xUnit and integrated CI pipelines on GitHub Actions.\n\nEDUCATION\nB.S. in Computer Science | Alexandru Ioan Cuza University of Ia\u0219i (2015 - 2019)',
  },
  {
    id: 'sample-5',
    name: 'Cristian Enache',
    cvFileName: 'Cristian_Enache_Node_Platform.pdf',
    fileSizeFormatted: '1.4 MB',
    cvRawText:
      'Cristian Enache\nEmail: cristian.enache@example.com | Location: Bra\u0219ov, Romania | GitHub: github.com/cristian-enache-dev\n\nPROFESSIONAL SUMMARY\nBackend Platform Engineer with 4 years of experience specializing in Node.js, TypeScript, and high-concurrency API platforms. Strong advocate of type safety, robust relational database architectures, and event-driven asynchronous queues.\n\nTECHNICAL SKILLS\n- Languages: TypeScript, JavaScript, Python, SQL\n- Frameworks: Node.js, NestJS, Express, FastAPI, Prisma, TypeORM\n- Databases: PostgreSQL, Redis, MongoDB\n- Queues & Messaging: BullMQ, RabbitMQ, AWS SQS\n- API Technologies: RESTful APIs, GraphQL (Apollo), WebSockets\n- Tools: Docker, AWS (S3, ECS), Git, GitHub Actions, Jest\n\nWORK EXPERIENCE\nBackend Engineer | Stripelet Payments Ltd\nFebruary 2022 - Present (2 years 7 months)\n- Developed resilient transaction settlement APIs using NestJS, TypeScript, and PostgreSQL.\n- Built asynchronous job processing workflows using BullMQ and Redis handling webhook retries and notifications.\n- Designed GraphQL schemas and RESTful web endpoints with comprehensive request validation and rate limiting.\n- Configured PostgreSQL connection pooling and implemented database partitioning for historical audit tables.\n\nBackend Developer | WebMesh Solutions\nOctober 2020 - January 2022 (1 year 4 months)\n- Engineered REST APIs for collaborative web platforms using Node.js and PostgreSQL.\n- Authored unit and integration test suites using Jest and Supertest achieving 88% branch coverage.\n- Deployed containerized applications to AWS ECS using Docker and CloudFormation.\n\nEDUCATION\nB.Sc. in Applied Informatics | Transilvania University of Bra\u0219ov (2016 - 2020)',
  },
  {
    id: 'sample-6',
    name: 'Vlad Diaconu',
    cvFileName: 'Vlad_Diaconu_Java_Backend.pdf',
    fileSizeFormatted: '1.6 MB',
    cvRawText:
      'Vlad Diaconu\nEmail: vlad.diaconu@example.com | Location: Cluj-Napoca, Romania | Portfolio: github.com/vlad-diaconu-fictional\n\nPROFESSIONAL SUMMARY\nEnterprise Backend Engineer with 5 years of experience architecting mission-critical financial backend services. Specializes in Java, Spring Boot, PostgreSQL, Kafka event streaming, and Clean Architecture principles.\n\nSKILLS & COMPETENCIES\n- Languages: Java (11/17), Python, SQL, Groovy\n- Frameworks: Spring Boot, Spring Cloud, Hibernate, JUnit 5, Mockito, FastAPI\n- Databases: PostgreSQL, Redis, Oracle\n- Messaging: Apache Kafka, RabbitMQ, AWS SQS\n- Architecture: Clean Architecture, SOLID, Microservices, Domain-Driven Design, REST, gRPC\n- Cloud & DevOps: Docker, Kubernetes, AWS, Jenkins, Datadog\n\nWORK EXPERIENCE\nSenior Backend Engineer | Stellaris Banking Technologies\nJuly 2021 - Present (3 years 2 months)\n- Architected enterprise banking microservices handling $20M+ in daily transaction volume with Java and Spring Boot.\n- Designed event-driven asynchronous processing pipelines with Apache Kafka and PostgreSQL.\n- Implemented strict database transactions, ACID guarantees, and optimistic locking to prevent double-spending race conditions.\n- Engineered RESTful service contracts and integrated Datadog APM tracing across 14 independent microservices.\n\nSoftware Engineer | CoreLink Software\nJune 2019 - June 2021 (2 years 1 month)\n- Built REST APIs and backend integrations with Java, Spring, and PostgreSQL.\n- Implemented Redis caching layers to reduce response times for frequently requested reference catalogs.\n- Authored unit tests with JUnit and Mockito, ensuring test coverage exceeded 90%.\n\nEDUCATION\nBachelor of Science in Computer Science | Babe\u0219-Bolyai University (2015 - 2019)',
  },
  {
    id: 'sample-7',
    name: 'George Iliescu',
    cvFileName: 'George_Iliescu_FullStack.pdf',
    fileSizeFormatted: '1.3 MB',
    cvRawText:
      'George Iliescu\nEmail: george.iliescu@example.com | Location: Bucharest, Romania | Website: georgeiliescu-dev.example.com\n\nPROFESSIONAL SUMMARY\nFull Stack Engineer with 3.5 years of experience delivering end-to-end web applications. 65% backend focus (Python FastAPI, PostgreSQL, Redis) and 35% modern frontend (React, TypeScript).\n\nSKILLS & TOOLS\n- Languages: Python, TypeScript, JavaScript, SQL, HTML5, CSS3\n- Backend: FastAPI, Django, Flask, SQLAlchemy, Celery, REST APIs\n- Frontend: React, Next.js, Tailwind CSS, Redux Toolkit\n- Databases: PostgreSQL, Redis, SQLite\n- Cloud & Tools: Docker, AWS (S3, EC2), Git, GitHub Actions, PyTest, Jest\n\nWORK EXPERIENCE\nFull Stack Engineer | PixelPulse Media\nJanuary 2022 - Present (2 years 8 months)\n- Developed core web platform features with Python FastAPI backends and React frontends.\n- Built RESTful APIs, authentication middleware (JWT / OAuth2), and background image processing tasks with Celery and Redis.\n- Designed database schemas and migration scripts using PostgreSQL and Alembic.\n- Containerized development workflows using Docker Compose, creating unified local dev environments.\n\nJunior Full Stack Developer | DevCraft Studio\nMarch 2021 - December 2021 (10 months)\n- Assisted in developing web applications using Django, React, and PostgreSQL.\n- Wrote API integration tests and fixed database query performance bottlenecks.\n\nEDUCATION\nB.S. in Computer Science | University of Bucharest (2017 - 2021)',
  },
  {
    id: 'sample-8',
    name: 'Elena Stan',
    cvFileName: 'Elena_Stan_Junior_Backend.pdf',
    fileSizeFormatted: '920 KB',
    cvRawText:
      'Elena Stan\nEmail: elena.stan@example.com | Location: Timi\u0219oara, Romania | GitHub: github.com/elena-stan-code\n\nPROFESSIONAL SUMMARY\nJunior Backend Developer with 1.5 years of professional experience building RESTful web services in Python and PostgreSQL. Motivated learner with strong fundamentals in algorithms, HTTP protocols, and database design.\n\nSKILLS & TECHNOLOGIES\n- Languages: Python, SQL, JavaScript, HTML/CSS\n- Frameworks: FastAPI, Flask, PyTest\n- Databases: PostgreSQL, SQLite\n- Tools & Practices: Git, Docker, Linux, REST APIs, CI/CD basics\n\nWORK EXPERIENCE\nJunior Backend Developer | BrightByte Labs\nFebruary 2023 - Present (1 year 7 months)\n- Developed and maintained REST API endpoints using Python and FastAPI for content management applications.\n- Wrote SQL queries, created database tables, and performed schema migrations in PostgreSQL.\n- Implemented comprehensive automated unit tests using PyTest, reaching 85% coverage on new endpoints.\n- Collaborated in daily agile standups, code reviews, and Git pull request workflows.\n\nSoftware Engineering Intern | CloudPoint Solutions\nJune 2022 - August 2022 (3 months)\n- Assisted backend team in refactoring internal reporting scripts into Python REST endpoints.\n- Documented API specifications using Swagger/OpenAPI.\n\nEDUCATION\nBachelor of Science in Computer Science | West University of Timi\u0219oara (2019 - 2023)',
  },
  {
    id: 'sample-9',
    name: 'Cosmin Tudor',
    cvFileName: 'Cosmin_Tudor_Data_Engineer.pdf',
    fileSizeFormatted: '1.4 MB',
    cvRawText:
      'Cosmin Tudor\nEmail: cosmin.tudor@example.com | Location: Cluj-Napoca, Romania | GitHub: github.com/cosmin-tudor-data\n\nPROFESSIONAL SUMMARY\nSenior Data Engineer with 4.5 years of experience architecting large-scale analytical data warehouses, ETL/ELT pipelines, and distributed data processing systems using Python, Spark, and PostgreSQL.\n\nSKILLS & TECHNOLOGIES\n- Languages: Python, SQL, Scala, Bash\n- Big Data & Orchestration: Apache Spark, Apache Airflow, dbt, Kafka\n- Databases & Warehouses: Snowflake, PostgreSQL, BigQuery, Redis\n- Cloud & Infrastructure: AWS (S3, EMR, Redshift), Docker, Terraform\n\nWORK EXPERIENCE\nSenior Data Engineer | DataSphere Insights\nMarch 2022 - Present (2 years 6 months)\n- Built automated batch and streaming data pipelines processing 2TB+ daily using Python and Apache Spark.\n- Optimized PostgreSQL and Snowflake schemas, materialized views, and partition keys for analytical reporting.\n- Orchestrated complex multi-stage DAGs using Apache Airflow and dbt on AWS infrastructure.\n- Designed data validation frameworks that improved overall pipeline data accuracy by 99.4%.\n\nData Engineer | MetricFlow Analytics\nOctober 2019 - February 2022 (2 years 5 months)\n- Developed Python ETL scripts to ingest third-party marketing and telemetry data into PostgreSQL.\n- Automated database maintenance and vacuuming tasks on self-hosted PostgreSQL instances.\n\nEDUCATION\nB.S. in Computer Science | Technical University of Cluj-Napoca (2015 - 2019)',
  },
  {
    id: 'sample-10',
    name: 'Simona Voinea',
    cvFileName: 'Simona_Voinea_DevOps_SRE.pdf',
    fileSizeFormatted: '1.5 MB',
    cvRawText:
      'Simona Voinea\nEmail: simona.voinea@example.com | Location: Bucharest, Romania | GitHub: github.com/simona-devops\n\nPROFESSIONAL SUMMARY\nDevOps & Site Reliability Engineer with 4 years of experience building scalable Kubernetes infrastructure, automated deployment pipelines, and deep observability stacks across multi-region AWS environments.\n\nTECHNICAL SKILLS\n- Cloud: AWS (EKS, RDS, S3, CloudFront, IAM), GCP\n- Infrastructure as Code: Terraform, Terragrunt, CloudFormation\n- Containers & Orchestration: Docker, Kubernetes, Helm, ArgoCD\n- Observability: Datadog, Prometheus, Grafana, OpenTelemetry, ELK Stack\n- Scripting & Automation: Python, Bash, Go, GitHub Actions, GitLab CI\n\nWORK EXPERIENCE\nSenior Site Reliability Engineer | CloudOps Network\nApril 2022 - Present (2 years 5 months)\n- Managed production Kubernetes clusters across 3 AWS regions running 200+ containerized microservices.\n- Implemented Datadog distributed tracing, APM, and custom alert monitors for critical payment workflows.\n- Built automated Terraform modules standardizing PostgreSQL RDS provisioning, automated backups, and read replicas.\n- Reduced infrastructure provisioning lead time from 3 days to 20 minutes with GitOps and ArgoCD.\n\nDevOps Engineer | InfraTech Solutions\nSeptember 2020 - March 2022 (1 year 7 months)\n- Automated CI/CD build and deployment pipelines for Python and Node.js applications using GitHub Actions.\n- Maintained Docker base images, scanning for CVE vulnerabilities and optimizing image layer caching.\n\nEDUCATION\nB.S. in Systems Engineering | University Politehnica of Bucharest (2016 - 2020)',
  },
  {
    id: 'sample-11',
    name: 'Florin Nistor',
    cvFileName: 'Florin_Nistor_Frontend_Lead.pdf',
    fileSizeFormatted: '1.6 MB',
    cvRawText:
      'Florin Nistor\nEmail: florin.nistor@example.com | Location: Ia\u0219i, Romania | Portfolio: florin-ui.example.com\n\nPROFESSIONAL SUMMARY\nLead Frontend Engineer with 6 years of experience crafting accessible, high-performance web user interfaces and design systems. Deep specialist in React, TypeScript, Next.js, and client-side performance.\n\nTECHNICAL SKILLS\n- Languages: TypeScript, JavaScript, HTML5, CSS3/SCSS\n- Frameworks & UI: React 18/19, Next.js, Vue.js, Tailwind CSS, Radix UI, Storybook\n- State & APIs: TanStack Query, Redux Toolkit, GraphQL (Apollo Client), REST\n- Testing & Tooling: Jest, React Testing Library, Playwright, Vite, Webpack\n\nWORK EXPERIENCE\nLead Frontend Developer | Nordic UI Studio\nMay 2021 - Present (3 years 4 months)\n- Directed frontend architecture for enterprise SaaS dashboards with React, TypeScript, and Tailwind CSS.\n- Optimized client-side Core Web Vitals, achieving 98+ Lighthouse scores across all key consumer views.\n- Implemented GraphQL client caching and optimistic UI updates using Apollo Client and TanStack Query.\n- Built an accessible design system with 40+ Radix UI primitives utilized across 6 company web properties.\n\nFrontend Software Engineer | PixelFront Agency\nJune 2018 - April 2021 (2 years 11 months)\n- Developed responsive SPAs for fintech and e-commerce clients using React and TypeScript.\n- Collaborated with UX designers in Figma to build interactive design tokens and prototypes.\n\nEDUCATION\nB.Sc. in Computer Science | Alexandru Ioan Cuza University of Ia\u0219i (2014 - 2018)',
  },
  {
    id: 'sample-12',
    name: 'Mircea Barbu',
    cvFileName: 'Mircea_Barbu_Mobile_Dev.pdf',
    fileSizeFormatted: '1.2 MB',
    cvRawText:
      'Mircea Barbu\nEmail: mircea.barbu@example.com | Location: Craiova, Romania | GitHub: github.com/mircea-barbu-apps\n\nPROFESSIONAL SUMMARY\nMobile Application Developer with 4 years of experience delivering cross-platform iOS and Android apps using Flutter, Dart, and Swift. Experienced in offline caching, push notifications, and mobile UI/UX.\n\nTECHNICAL SKILLS\n- Mobile Platforms: Flutter, Dart, Swift, iOS SDK, Android SDK, Kotlin\n- State Management: Bloc, Riverpod, Provider\n- Networking & Storage: REST APIs, GraphQL client, SQLite, Hive, Firebase Cloud Firestore\n- Tools & CI: Xcode, Android Studio, Fastlane, GitHub Actions, Firebase Crashlytics\n\nWORK EXPERIENCE\nSenior Mobile Developer | AppSphere Mobile\nMarch 2022 - Present (2 years 6 months)\n- Developed and published 3 production Flutter mobile applications with over 500,000 active downloads.\n- Integrated RESTful backend endpoints with robust offline synchronization and local caching using Hive.\n- Implemented real-time push notifications, deep linking, and automated release tracks using Fastlane.\n- Maintained 99.8% crash-free sessions across diverse iOS and Android hardware configurations.\n\nMobile Software Engineer | SwiftWorks Studio\nSeptember 2020 - February 2022 (1 year 6 months)\n- Built native iOS applications using Swift and UIKit/SwiftUI.\n- Integrated third-party payment SDKs (Stripe, Apple Pay) and analytics tracking.\n\nEDUCATION\nB.S. in Computer Science | University of Craiova (2016 - 2020)',
  },
  {
    id: 'sample-13',
    name: 'Robert Moraru',
    cvFileName: 'Robert_Moraru_Embedded_C.pdf',
    fileSizeFormatted: '1.8 MB',
    cvRawText:
      'Robert Moraru\nEmail: robert.moraru@example.com | Location: Sibiu, Romania | LinkedIn: linkedin.com/in/robert-moraru-fictional\n\nPROFESSIONAL SUMMARY\nEmbedded Systems & Firmware Engineer with 7 years of experience programming low-level microcontrollers, real-time operating systems (RTOS), and industrial automotive telemetry sensors in C and C++.\n\nTECHNICAL SKILLS\n- Languages: Embedded C, C++, Assembly (ARM), Python (scripting)\n- Microcontrollers & Arch: ARM Cortex-M, STM32, ESP32, PIC, AVR\n- Protocols & Buses: CAN Bus, SPI, I2C, UART, Modbus, BLE\n- Systems & Tools: FreeRTOS, Embedded Linux, Keil uVision, Oscilloscopes, Logic Analyzers, JTAG\n\nWORK EXPERIENCE\nSenior Firmware Engineer | AutoControl Telematics\nNovember 2020 - Present (3 years 10 months)\n- Developed safety-critical embedded firmware in C for vehicle telematics control units running FreeRTOS.\n- Implemented CAN Bus protocol drivers transmitting engine sensor telemetry to edge storage.\n- Optimized power consumption on battery-powered IoT devices, extending field operational lifespan by 35%.\n- Performed hardware-in-the-loop (HIL) testing and bare-metal debugging with digital oscilloscopes and JTAG.\n\nEmbedded Software Developer | MicroSensors SRL\nAugust 2017 - October 2020 (3 years 3 months)\n- Programmed STM32 microcontrollers in C for precision temperature and pressure sensor calibration.\n- Wrote Python scripts to automate hardware validation testing in manufacturing lines.\n\nEDUCATION\nMaster of Science in Electronics | Lucian Blaga University of Sibiu (2015 - 2017)\nBachelor of Science in Electronics | Lucian Blaga University of Sibiu (2011 - 2015)',
  },
  {
    id: 'sample-14',
    name: 'Anca Moldovan',
    cvFileName: 'Anca_Moldovan_QA_Automation.pdf',
    fileSizeFormatted: '1.4 MB',
    cvRawText:
      'Anca Moldovan\nEmail: anca.moldovan@example.com | Location: Cluj-Napoca, Romania | GitHub: github.com/anca-moldovan-qa\n\nPROFESSIONAL SUMMARY\nSenior QA Automation Engineer with 4.5 years of experience developing comprehensive end-to-end, regression, and API automated testing frameworks for distributed web applications.\n\nTECHNICAL SKILLS\n- Test Automation: Playwright, Cypress, Selenium WebDriver, Postman, Supertest, PyTest\n- Languages: TypeScript, JavaScript, Python\n- CI/CD & Cloud: GitHub Actions, Jenkins, Docker, AWS Device Farm\n- Methodologies: BDD (Cucumber), TDD, Agile QA, Performance Testing (k6, JMeter)\n\nWORK EXPERIENCE\nSenior QA Automation Engineer | QualityFirst Technologies\nApril 2022 - Present (2 years 5 months)\n- Designed and maintained cross-browser end-to-end automation frameworks with Playwright and TypeScript.\n- Built automated REST API regression test suites in Postman and PyTest, integrated directly into PR merge gates.\n- Executed load and stress testing using k6, identifying backend performance bottlenecks before product launches.\n- Reduced manual regression testing turnaround time from 2 days to 30 minutes in CI pipelines.\n\nQA Engineer | TestMatrix Solutions\nSeptember 2019 - March 2022 (2 years 7 months)\n- Authored automated UI tests using Cypress and Selenium WebDriver.\n- Logged, tracked, and verified defect resolutions in Jira in collaboration with backend and frontend engineers.\n\nEDUCATION\nB.S. in Computer Science | Babe\u0219-Bolyai University (2015 - 2019)',
  },
  {
    id: 'sample-15',
    name: 'Victor Oprea',
    cvFileName: 'Victor_Oprea_Backend_Developer.pdf',
    fileSizeFormatted: '1.5 MB',
    cvRawText:
      'Victor Oprea\nEmail: victor.oprea@example.com | Location: Timi\u0219oara, Romania | GitHub: github.com/victor-oprea-backend\n\nPROFESSIONAL SUMMARY\nBackend Web Developer with 3+ years of experience engineering secure RESTful APIs, database models, and background task queues using Python, Django, FastAPI, and PostgreSQL.\n\nTECHNICAL SKILLS\n- Languages: Python, SQL, JavaScript\n- Frameworks: Django, Django REST Framework, FastAPI, Celery\n- Databases & Caching: PostgreSQL, Redis, SQLite\n- Cloud & Tools: Docker, AWS (S3, RDS), Git, GitHub Actions, Linux, PyTest\n\nWORK EXPERIENCE\nBackend Software Developer | Omnicraft Web Services\nJanuary 2023 - Present (1 year 8 months)\n- Developed and maintained core API endpoints for client subscription platforms using Python FastAPI and PostgreSQL.\n- Implemented asynchronous task workflows using Celery and Redis for automated reporting and email notifications.\n- Designed relational schemas and database indexes, ensuring sub-100ms response times for high-frequency queries.\n- Integrated third-party payment gateways (Stripe, PayPal) and webhook notification listeners.\n\nJunior Backend Developer | ByteForge Systems\nJune 2021 - December 2022 (1 year 7 months)\n- Built internal tooling and data management endpoints using Django REST Framework and PostgreSQL.\n- Created unit tests with PyTest and mocked external service responses, maintaining 85% code coverage.\n- Managed Git feature branches and contributed to peer code reviews.\n\nEDUCATION\nBachelor of Science in Computer Science | Politehnica University of Timi\u0219oara (2017 - 2021)',
  },
];
